site_name: OakVar
site_url: https://oakvar.com
nav:
  - Home: index.md
  - Install: 
    - System: install_system.md
    - Modules: install_modules.md
  - Overview: overview.md
  - Tutorial: tutorial.md
  - VCF2VCF: vcf2vcf.md
  - Command-line interface: cli.md
  - Graphical user interface: gui.md
  - Publishing your module: register.md
  - Developer guide: 
    - Modules: devguide_modules.md
    - Workflows: devguide_workflows.md
    - Debugging: devguide_debugging.md
  - API:
    - oakvar.api: 
      - api/index.md
      - config: api/config.md
      - module: api/module.md
      - new: api/new.md
      - store:
        - api/store.md
        - account: api/store_account.md
      - system: api/system.md
  - Release notes &#128279: "https://github.com/rkimoakbioinformatics/oakvar/releases"
  - Repository &#128279: "https://github.com/rkimoakbioinformatics/oakvar"
  - License &#128279: "https://github.com/rkimoakbioinformatics/oakvar/blob/master/LICENSE"
  - Sponsor &#128279: "https://github.com/sponsors/rkimoakbioinformatics"
theme: 
  name: material
  logo: images/logo.png
markdown_extensions:
  - attr_list
  - tables
plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_source: false
            heading_level: 2
            docstring_section_style: spacy
            separate_signature: true
watch:
  - /mnt/d/Git/oakvar/oakvar/api
